version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    container_name: backend1
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend1
    stdin_open: true
    tty: true
    depends_on:
      - backend
